### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by Aimiyoo** [wikimedia/operations-software-druid_exporter#1]
1$ virtualenv .venv
2$ .venv/bin/python setup.py build
3$ .venv/bin/python setup.py install
4$.venv/bin/druid_exporter --listen localhost:8000

**Comment by elukey** [comment]
Hi! Sorry I didn't get the meaning of this issue, are you suggesting to add this to the README?

**Comment by Aimiyoo** [comment]
what I mean is that I set up the exporter with "virtualenv .venv .venv/bin/python setup.py .venv/bin/druid_exporter" as you say, but it did't work.
So I set up it according to the above.

**Comment by elukey** [comment]
ah nice, thanks for the feedback! Going to check it later on and fix the documentation accordingly!

**Comment by Aimiyoo** [comment]
Hello, what confused me is that how the druid export detect the durid service, I did't find 8082 port or any configuration related to druid service in the code, can you help me, thank you.

**Comment by elukey** [comment]
I tried to explain the idea in https://github.com/wikimedia/operations-software-druid_exporter#how-does-it-work, not sure if it is clear enough (feedback welcome!). Basically you set all the Druid daemons that you need to instrument with a http emitter: this will cause a series of POSTS to be sent to the druid_exporter, that will collect the metrics and return them when polled by prometheus.

**Comment by Aimiyoo** [comment]
thank you very much, I also find "Druid must be configured to POST metrics to the prometheus druid exporter" in [https://phabricator.wikimedia.org/T177459](https://phabricator.wikimedia.org/T177459), I will try it later, thank you again.

**Comment by Aimiyoo** [comment]
I read the website above, what you mean is set "druid.emitter.http.recipientBaseUrl" to "localhost:8000", is it right?

**Comment by elukey** [comment]
We use something like the following:

```
druid.emitter=composing
druid.emitter.composing.emitters=["logging","http"]
druid.emitter.http.recipientBaseUrl=http://localhost:8000/
```

This allows us to have metrics logged on file (that you can filter via log4j rules etc..) and also sent to the druid prometheus agent via HTTP POST.

**Comment by Aimiyoo** [comment]
oh, nice, the exporter is woring very well, next step I will write other metrics according to my needs, thank you for  your time.

**Comment by elukey** [comment]
Really glad that you are enjoying it! Going to close the issue if you don't mind, feel free to re-open if something is missing.
