### ISSUE TITLE
The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported

### ISSUE THREAD

**Issue by danghuagood** [wikimedia/operations-software-druid_exporter#18]
**druid(version:0.17.1) common.runtime.properties:**
druid.emitter=composing
druid.emitter.composing.emitters=["logging", "http"]
druid.emitter.logging.logLevel=info
druid.emitter.http.flushMillis=60000
druid.emitter.http.flushTimeOut=60000
druid.emitter.http.flushCount=500
druid.emitter.http.recipientBaseUrl=http://10.10.18.102:10010/
druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.java.util.metrics.SysMonitor"]

**historical runtime.properties:**
druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor","org.apache.druid.server.metrics.HistoricalMetricsMonitor", "org.apache.druid.java.util.metrics.JvmMonitor"]

**run druid_exporter(version:upstream-0.9) with following command:**
druid_exporter -d -l 0.0.0.0:10010 ./example_druid_v_0_17_0.json

**stdout of the log:**
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.951Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 65041136, 'poolKind': 'nonheap', 'poolName': 'Metaspace'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.951Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 65041136, 'poolKind': 'nonheap', 'poolName': 'Metaspace'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.952Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 0, 'poolKind': 'nonheap', 'poolName': 'Metaspace'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.952Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 0, 'poolKind': 'nonheap', 'poolName': 'Metaspace'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.952Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/max', 'value': 1073741824, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.952Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/max', 'value': 1073741824, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/committed', 'value': 8519680, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/committed', 'value': 8519680, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 8152496, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 8152496, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 0, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.953Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 0, 'poolKind': 'nonheap', 'poolName': 'Compressed Class Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/max', 'value': 1179123712, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/max', 'value': 1179123712, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/committed', 'value': 680001536, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/committed', 'value': 680001536, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 207383192, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.954Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/used', 'value': 207383192, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.955Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 537395200, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:21:30.955Z', 'service': 'druid/historical', 'host': '10.10.18.102:8083', 'version': '0.17.1', 'metric': 'jvm/pool/init', 'value': 537395200, 'poolKind': 'heap', 'poolName': 'PS Eden Space'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'softIrq'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'softIrq'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'irq'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'irq'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'sys'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'sys'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'user'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'user'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'nice'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '6', 'cpuTime': 'nice'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'wait'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'wait'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'stolen'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'stolen'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'softIrq'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'softIrq'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'irq'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'irq'}
DEBUG:druid_exporter.exporter:Processing datapoint: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'sys'}
DEBUG:druid_exporter.collector:The following datapoint is not supported, either because the 'feed' field is not 'metrics' or the metric itself is not supported: {'feed': 'metrics', 'timestamp': '2020-08-14T03:31:54.846Z', 'service': 'druid/coordinator', 'host': '10.18.65.154:8081', 'version': '0.17.1', 'metric': 'sys/cpu', 'value': 0, 'cpuName': '7', 'cpuTime': 'sys'}
10.18.65.154 - - [2020-08-14 11:31:55] "POST / HTTP/1.1" 200 75 0.185880

**Comment by elukey** [comment]
Hi! The datapoints listed in the DEBUG messages are not listed in the example json file, so they are not processed. You'd need to add them in there if you want to them published. The error msg is not clear enough though, I'll try to improve (a while ago in fact metrics were hardcoded in the exporter's code, meanwhile now the user can specify them in a config file).

**Comment by elukey** [comment]
done with https://github.com/wikimedia/operations-software-druid_exporter/commit/d94ede128bbc3faba0fabc4be95fa9cfca7f87ce

Also released version 0.10 :)
