### ISSUE TITLE
Overlord not exists in allowed daemon labels

### ISSUE THREAD

**Issue by busecolak** [wikimedia/operations-software-druid_exporter#8]
Hi!

My druid cluster has separate Overlord and Coordinator services. I would like to configure the exporter to collect metrics from both services. But the overlord is not included in allowed daemons. I am getting the following error:
`RuntimeError: Config error: daemon name overlord not among the list of allowed Druid daemons ['middlemanager', 'historical', 'peon', 'broker', 'coordinator']`

Could you please add overlord to allowed daemon list, thanks.

**Comment by elukey** [comment]
@busecolak merged your gerrit patch! Thanks!
